### ISSUE TITLE
ADA Support - Record Initialisers

### ISSUE THREAD

**Issue by sara-db** [diffblue/gnat2goto#10]
@smowton commented on [Fri Apr 28 2017](https://github.com/diffblue/security-scanner/issues/119)

Default-initialise records if their type gives default values for particular fields.

**Comment by smowton** [comment]
Done for everything except variant records as of https://github.com/diffblue/gnat2goto/commit/a6332f2c7b1d13a2aac71cfe29c3f70f1cbd1e2c

**Comment by smowton** [comment]
Fully implemented as of https://github.com/diffblue/gnat2goto/commit/47f7438f20119619a4cb01d2910947193dbc88fa
