### ISSUE TITLE
Array assignment non-termination

### ISSUE THREAD

**Issue by sonodtt** [diffblue/gnat2goto#106]
Assignment of an array does not terminate in symex loop unwinding

e.g.
procedure Basic_Failure is
   type Arr1 is array (1 ..7) of Integer;
   Actual1 : Arr1 := (1,2,3,4,5,6,7);
begin
   Actual1 (1 .. 2) := Actual1 (3 .. 5);
end Basic_Failure;

Termination can be forced by setting the length used in the function Get_Array_Copy_Function directly.

**Comment by xbauch** [comment]
Array assignment no longer causes non-termination.
