### ISSUE TITLE
Assignment of an array, upon termination, causes invariant violation

### ISSUE THREAD

**Issue by sonodtt** [diffblue/gnat2goto#107]
The following does not terminate in symex loop unwinding.
procedure Basic_Failure is
   type Arr1 is array (1 ..7) of Integer;
   Actual1 : Arr1 := (1,2,3,4,5,6,7);
begin
   Actual1 (1 .. 2) := Actual1 (3 .. 5);
end Basic_Failure;

When termination is forced (by passing a fixed array size) then an invariant violation is printed:

--- begin invariant violation report ---
Invariant check failed
File: <path...>/cbmc/src/solvers/flattening/boolbv_width.cpp:202 function: get_entry
Condition: false
Reason: Unimplemented
Backtrace:
0   cbmc                                0x0000000104168afc _Z15print_backtraceRNSt3__113basic_ostreamIcNS_11char_traitsIcEEEE + 92
1   cbmc                                0x0000000104169ad9 _Z13get_backtracev + 761
2   cbmc                                0x00000001042990f1 _Z29invariant_violated_structuredI17invariant_failedtJRKNSt3__112basic_stringIcNS1_11char_traitsIcEENS1_9allocatorIcEEEEEENS1_9enable_ifIXsr3std10is_base_ofIS0_T_EE5valueEvE4typeES9_S9_iS9_DpOT0_ + 49
3   cbmc                                0x00000001042990b3 _Z25invariant_violated_stringRKNSt3__112basic_stringIcNS_11char_traitsIcEENS_9allocatorIcEEEES7_iS7_S7_ + 51
4   cbmc                                0x0000000103e006c1 _ZNK13boolbv_widtht9get_entryERK5typet + 15905
5   cbmc                                0x0000000103d79c4d _ZNK13boolbv_widthtclERK5typet + 253
6   cbmc                                0x0000000103d87e4a _ZN7boolbvt14convert_symbolERK5exprt + 106
7   cbmc                                0x0000000103d7cdee _ZN7boolbvt17convert_bitvectorERK5exprt + 4894
8   cbmc                                0x0000000103e17f8f _ZN12bv_pointerst17convert_bitvectorERK5exprt + 8543
9   cbmc                                0x0000000103d7a9c9 _ZN7boolbvt10convert_bvERK5exprtN6nonstd13optional_lite8optionalImEE + 3241
10  cbmc                                0x0000000103d8f0da _ZN7boolbvt27boolbv_set_equality_to_trueERK11equal_exprt + 410
11  cbmc                                0x0000000103d8f60d _ZN7boolbvt6set_toERK5exprtb + 1085
12  cbmc                                0x0000000103a313c4 _ZN19decision_proceduret11set_to_trueERK5exprt + 52
13  cbmc                                0x0000000103a2d8e1 _ZNK22symex_target_equationt19convert_assignmentsER19decision_proceduret + 705
14  cbmc                                0x0000000103a2cf81 _ZN22symex_target_equationt7convertER10prop_convt + 65
15  cbmc                                0x00000001034f8aeb _ZN4bmct13do_conversionEv + 91
16  cbmc                                0x00000001034e6a6e _ZN19bmc_all_propertiestclEv + 286
17  cbmc                                0x00000001034ee24e _ZN4bmct14all_propertiesERK15goto_functionstR10prop_convt + 158
18  cbmc                                0x00000001034fe8b4 _ZN4bmct6decideERK15goto_functionstR10prop_convt + 404
19  cbmc                                0x00000001034fc7d8 _ZN4bmct7executeER20abstract_goto_modelt + 5048
20  cbmc                                0x00000001034fe70d _ZN4bmct3runER20abstract_goto_modelt + 45
21  cbmc                                0x000000010350057f _ZN4bmct24do_language_agnostic_bmcERK22path_strategy_choosertRK8optionstR20abstract_goto_modeltR19ui_message_handlertNSt3__18functionIFvRS_RK13symbol_tabletEEENSB_IFbvEEE + 4303
22  cbmc                                0x0000000103527838 _ZN19cbmc_parse_optionst4doitEv + 5720
23  cbmc                                0x00000001041dda09 _ZN19parse_options_baset4mainEv + 601
24  cbmc                                0x00000001034e3872 main + 66
25  libdyld.dylib                       0x00007fff6c2fe015 start + 1
26  ???                                 0x0000000000000002 0x0 + 2

--- end invariant violation report ---

**Comment by xbauch** [comment]
Array assignment now behaves correctly (at least in the case above).
