### ISSUE TITLE
alloc and malloc generated entry in symbol table has a statement of type "irep" but cbmc issues no warnings

### ISSUE THREAD

**Issue by sonodtt** [diffblue/gnat2goto#109]
We are not entirely sure of this error (cbmc issues no warning) but it is an unusual expression in the symbol table and within the context of the array implementation issues, needs some investigation. 

Symbol......: __ada_dup_array1
Pretty name.: __ada_dup_array1
Module......: 
Base name...: __ada_dup_array1
Mode........: C
Type........: int * (int *ptr, int len)
Value.......: {
  int *__new_array2;
  __new_array2 = irep("(\"side_effect\" \"type\" (\"pointer\" \"\" (\"signedbv\" \"width\" (\"32\")) \"width\" (\"64\")) \"statement\" (\"cpp_new[]\") \"size\" (\"symbol\" \"type\" (\"signedbv\" \"width\" (\"32\")) \"identifier\" (\"__ada_dup_array1len\") \"range_check\" (\"0\") \"#source_location\" (\"source_location\")) \"range_check\" (\"0\") \"#source_location\" (\"source_location\"))");
  __array_dup_fun_lhs3=__ada_copy_array1(__new_array2, ptr, len);
  return __new_array2;
}
Flags.......:
Location....:

**Comment by xbauch** [comment]
It indicates that the irep was malformed. With the new implementation it no longer happens.
