### ISSUE TITLE
Please can you change the review and merge policy?

### ISSUE THREAD

**Issue by martin-cs** [diffblue/gnat2goto#341]
Hi all (esp @chrisr-diffblue ),

As there are now less people working on this project, please could you reduce the number of reviews required to merge a PR to one?

Cheers,
 - Martin

**Comment by chrisr-diffblue** [comment]
Hi Martin! I've just changed the branch protections for `master` to allow merges with one approving review. If I've been inadvertently blocking anything, then my apologies!

**Comment by martin-cs** [comment]
Thank you for the super-prompt response!  I think the main block has been the changes that AdaCore made meaning Travis broke but I hope that https://github.com/diffblue/gnat2goto/pull/342 resolves this.
