### ISSUE TITLE
Please can you look at the travis / github link? It seems to be broken at the moment

### ISSUE THREAD

**Issue by martin-cs** [diffblue/gnat2goto#348]
Hi @chrisr-diffblue and @thk123 

Sorry to trouble you but please can you look at what is going on with the github / travis connection?  The CI runs seem to have completed but github is not recognising it.  I don't have the access rights to investigate.

Thanks.

**Comment by chrisr-diffblue** [comment]
I'll try restarting builds on Travis - there are occasionally network glitches that mean travis doesn't talk to github...

**Comment by martin-cs** [comment]
Thanks for the prompt action.  Note that a whole load of them are stopped, including ones that haven't run CI for some time.

**Comment by chrisr-diffblue** [comment]
Yeah - If restarting the travis jobs doesn't do it, then it might be necessary to rebase+force push each PR individually to get github to re-post a travis request. I'll see what happens and update this ticket when the restarted travis jobs complete.

**Comment by martin-cs** [comment]
Thanks!  Ironically rebase+force push on each PR was what preceded this error!

**Comment by martin-cs** [comment]
I am starting to see some completed results so this may be fine...

**Comment by chrisr-diffblue** [comment]
OK, so it looks like most of them a restart was enough. For #320 it'll need a rebase+push I think.

**Comment by chrisr-diffblue** [comment]
It doesn't happen often, but there do seem to be odd windows of time where the github/travis hooks just go AWOL for an hour or two. I think its outside of our control.

**Comment by martin-cs** [comment]
Thank you for the fast response and resolution; appreciated.
