### ISSUE TITLE
Please can you grant some of my team members write access?

### ISSUE THREAD

**Issue by martin-cs** [diffblue/gnat2goto#378]
To increase the pool of reviewers, please can you give @jeremycrisp and @johnfxgalea write access?

**Comment by chrisr-diffblue** [comment]
Hi Martin - I would have done this myself, but don't quite have the access rights for this (I'm 'admin', but not 'admin' enough, apparently...). I've pinged the appropriate people here and there should be invites coming out soon.

**Comment by chrisr-diffblue** [comment]
Invites have been sent out. @jeremycrisp and @johnfxgalea will need to accept the invites before the write access kicks in.

**Comment by martin-cs** [comment]
Amazing!  Thank you.
