### ISSUE TITLE
CI seems to be broken, possibly due to changes at Travis

### ISSUE THREAD

**Issue by martin-cs** [diffblue/gnat2goto#383]
[ Paging @chrisr-diffblue @peterschrammel and @NlightNFotis ]

The CI for gnat2goto does not seem to be working.  I don't know if it is a temporary glitch, a brown out or the final black out caused by the changes at Travis.  As this will be charged to Diffblue's account, I figured we should talk to you before changing anything.  As I see it, the options are:

1. You change how / where the CI gets run.
2. We set up CI on https://github.com/martin-cs/gnat2goto and all of our future PRs goes to that.

Which works best for you?

**Comment by martin-cs** [comment]
Thanks for the fast response @chrisr-diffblue .  Would you be OK with one of our team submitting a PR to move the CI to github actions or do (collective) you want to do it?

**Comment by chrisr-diffblue** [comment]
Realistically we won't have the bandwidth to do it, so if your team do, that's fine by me :-) @NlightNFotis has recent experience from moving CBMC to github so he might be able to answer questions if thats a help. Also, if we need to do anything admin-wise to hookup between the gnat2goto repo and the github actions, just ping me and I'll make sure they happen.

**Comment by martin-cs** [comment]
Thank you.

**Comment by martin-cs** [comment]
So it appears that it was a passing issue and it is now working but the migration will need to happen sooner rather than later.

**Comment by chrisr-diffblue** [comment]
Yeah, looks like Travis are about to go through some sort of transition. For what it's worth, internally at Diffblue were using GitHub actions with our own mixture of cloud hosted runners and self hosted runners. For CBMC we are using GitHub actions with github's hosted runners. In both case it seems to have been pretty reliable. GitHub actions themselves are a little quirky, but that only really seems to bite if you want to do any complex logic around what tests to run on what builds, or things like triggering actions based on labels. I think for gnat2goto there should be nothing problematic.

**Comment by martin-cs** [comment]
@chrisr-diffblue Please could you disable Travis CI so that we can work on a PR to replace it?

**Comment by chrisr-diffblue** [comment]
@martin-cs I'm away from keyboard right now, but will take a look at disabling Travis later today. Do you have a time frame for the replacement? And has travis now completely died, or just another glitch?

**Comment by martin-cs** [comment]
@chrisr-diffblue Thanks.  Travis is properly dead this time.  The replacement will be the next or next but one PR we merge and hopefully next week.

**Comment by chrisr-diffblue** [comment]
@martin-cs I think I've removed the various bits of admin setup which should have disabled Travis now. Please let me know if that's still not enough and I'll dig further :-) Notably, I've _not_ removed the `.travis.yml` file from the repo itself, as I figured that might still be useful to crib workflow commands from. I'd suggest that once you have a PR up/merged/working for the replacement, we then PR a removal of the travis.yml file as well.

**Comment by martin-cs** [comment]
Thanks.  Based on https://github.com/diffblue/gnat2goto/pull/390 which I have just opened, github is still waiting for Travis to do something.

Thanks for leaving the `.travis.yml` file, that will indeed be useful!

**Comment by chrisr-diffblue** [comment]
Ah, apologies - pro-tip - when you make a configuration change to branch restrictions in the admin UI, it really helps if you _also_ click the cryptically named "Save" button afterwards.... 🤦 #390 should be ready to merge with an approving review now...

**Comment by martin-cs** [comment]
Ah, yes, that seems to have done the trick!  Thank you.

**Comment by johnfxgalea** [comment]
I have addressed this issue by migrating gnat2goto's CI from using travis to github actions. PR coming up!
