### ISSUE TITLE
Please can you give John write access?

### ISSUE THREAD

**Issue by martin-cs** [diffblue/gnat2goto#388]
@johnfxgalea is working with @tjj2017 and I and it would be really good if he could review / authorise / sign-off patches.  Please @chrisr-diffblue or @NlightNFotis (?)  could you give him write access?

**Comment by johnfxgalea** [comment]
I already have write access (https://github.com/diffblue/gnat2goto/issues/378).

**Comment by martin-cs** [comment]
It may be that he needs "review" access as well?  Anyway, can someone with access to the setting of this repository make it so that @johnfxgalea can approve PRs?

**Comment by martin-cs** [comment]
Nevermind!  Looks like it works!
