### ISSUE TITLE
Better support for array semantics in gnat2goto

### ISSUE THREAD

**Issue by NlightNFotis** [diffblue/gnat2goto#70]
While getting https://github.com/diffblue/cbmc/pull/3112 cleaned up, we noticed that `gnat2goto` is using `cpp new` array initialisation semantics. There's no clean way to handle this in cbmc right now, so we have to check if there's a better way to handle the semantics of array initialisation in `gnat2goto`.

**Comment by xbauch** [comment]
We no longer use cpp new.
