### ISSUE TITLE
Travis CI builds more of CBMC than we actually need for gnat2goto testing

### ISSUE THREAD

**Issue by chrisr-diffblue** [diffblue/gnat2goto#73]
Currently Travis CI uses a standard 'cmake' build command for building CBMC. By default, this builds *everything* in the CBMC repo - cbmc, goto-analyser, jbmc, unit tests, etc, etc. However, the only reason we don't actually need all those targets built. e.g. we don't need to build cbmc unit test binaries, because we are not running them. Neither do we need to build the java tools.

We should limit the list of targets we build to just the tools we actually care about for testing.

**Comment by martin-cs** [comment]
Resolved by https://github.com/diffblue/gnat2goto/pull/391 in a round about way.  It caches the build of CBMC so we should only ever need to rebuild it when we update the git submodule.
