### ISSUE TITLE
ADA Support - Variant records

### ISSUE THREAD

**Issue by sara-db** [diffblue/gnat2goto#8]
@jgwilson42 commented on [Thu Mar 30 2017](https://github.com/diffblue/security-scanner/issues/67)

**Comment by smowton** [comment]
These work by virtue of array support, but need record initialiser support so that raw declarations work properly.

**Comment by smowton** [comment]
Appears to be fully working as of https://github.com/diffblue/gnat2goto/commit/47f7438f20119619a4cb01d2910947193dbc88fa
