### ISSUE TITLE
All enum values are non det

### ISSUE THREAD

**Issue by NlightNFotis** [diffblue/gnat2goto#97]
This is related to what Hannes has mentioned in #85.

For code like this:

```
type T is (A, B);

pragma Assert (A /= B);
```

the assertion fails.

**Comment by hannes-steffenhagen-diffblue** [comment]
Note that this example in particular fails for a different reason than you'd expect, as the frontend helpfully simplifies `A /= B` to `standard__boolean__true` (which is also nondet at the moment).

If you provide wrapper functions `function Get_A return T is (A); function Get_B return T is (B);` then the issue becomes apparent with `Get_A /= Get_B`.

**Comment by hannes-steffenhagen-diffblue** [comment]
Was fixed
